#!/bin/bash
#
# * should be run as www-data
# * checks out DOC
# * generates HTML from LaTeX
# 
# Mirko Saam
#
CVSWORK=/vol/neuro/nase/www-nase-copy
MAKEDOC=$CVSWORK/doc/www-bin/makedoc

USERNAME=`id --name --user`
if ! [ "$USERNAME" == "www-data" ] ; then
  echo "User www-data should run $0"
exit 1
fi     


CVSROOT=/vol/neuro/nase/IDLCVS
cd $CVSWORK
cvs -d $CVSROOT checkout doc

cd $CVSWORK/doc/standards
ln -sf $CVSWORK/nase/header.pro $CVSWORK/doc/header.pro.tex
$MAKEDOC standards
$MAKEDOC cvs

cd $CVSWORK/doc/workshop
$MAKEDOC workshop
$MAKEDOC todo

cd $CVSWORK/doc/simulation
$MAKEDOC neurontypes

exit 0
